<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.27.3" />
    <PackageReference Include="Grpc.Tools" Version="2.66.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="Protos/gtfs-realtime.proto" GrpcServices="None" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../TransitGuard.Core/TransitGuard.Core.csproj" />
  </ItemGroup>
</Project>
